### ISSUE TITLE
Event delegation is not supported because color-changed event does not bubble

### ISSUE THREAD

**Issue by Webbeh** [web-padawan/vanilla-colorful#21]
Hi,

Loading the vanilla-colorful module works well on a static HTML page : the color picker shows and the "color-changed" event is fired properly.

However, if I dynamically add a <hex-color-picker> element to the DOM using jQuery, the color picker does appear in the page, but no "color-changed" event is fired.

![image](https://user-images.githubusercontent.com/1530837/102893774-68c29b00-4462-11eb-8eae-44c6e6e45137.png)
You can see the difference in the inspector between the 8th line from the top (static, in the DOM before importing the module) and the 4th line from the bottom (dynamically added element).

Is there any way to "reload" the module dynamically, or to force adding the custom element ?

I import the module through UnPKG.

Thank you!

**Comment by web-padawan** [comment]
Hi, thanks for the issue. Could you please provide a code example to investigate? A jsbin / jsfiddle would be really nice.

**Comment by Webbeh** [comment]
This has the same behaviour if I create the element manually with `document.createElement("hex-color-picker")` instead of cloning an HTML template.

**Comment by Webbeh** [comment]
https://jsfiddle.net/9xbe31kd/2/

**Comment by Webbeh** [comment]
Any way I can help ?

**Comment by web-padawan** [comment]
Thanks for the examples, looks like this is a bug. I will investigate why the event doesn't fire and fix that.

**Comment by web-padawan** [comment]
I have added a test that confirms the `color-changed` event is dispatched when the element is attached: https://github.com/web-padawan/vanilla-colorful/commit/cd59bf355afff57607b0b8f59363ac0d8e51bfe2

Speaking about your examples, let me explain why they do not work as you expect:

1. The first example below (without the delegation) does not work and that's intended, see the documentation:

> Direct events are only attached to elements at the time the .on() method is called. In this case, since our new anchor did not exist when .on() was called, it does not get the event handler.

```js
$("hex-color-picker").on("color-changed", alarm)
```

2. The second example doesn't work because the `color-changed` event does not have `bubbles: true`:
 
```js
 $("#container").on("color-changed", "hex-color-picker", alarm)
```

I agree it's counter-intuitive. For example, the native [`input`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) event bubbles and that makes event delegation possible. 
So I think this behavior needs to be changed in order to support bubbling. Will submit a PR to do it.

**Comment by Webbeh** [comment]
Will test later this week. Thanks for the fix!

**Comment by web-padawan** [comment]
Thanks, here is the jsbin which now works for me: https://jsbin.com/dopocin/edit?html,js,console,output

**Comment by Webbeh** [comment]
Was there a reason for bubbling not to be enabled? I did think that was the reason why the events didn't get registered (since they didnt even for static pages).

**Comment by web-padawan** [comment]
There is no reason, I just forgot about the event delegation, that's why I didn't add `bubbles: true`.

Actually, I'm using Polymer at work, its two-way data binding system uses `*-changed` event names, and those events are [non-bubbling](https://github.com/Polymer/polymer/blob/17720d01883358c4bb6ac02fc9e51a6cc2336e44/lib/mixins/property-effects.js#L328). But with bubbling enabled this component would still work with Polymer, so I don't see any problem here.

**Comment by Webbeh** [comment]
I can now confirm that the changes have been propagated through unpkg properly and are working with my code.

Thank you!
